### ISSUE TITLE
remove ssh folder dependency to create infrastructure 

### ISSUE THREAD

**Issue by snps-gdinesh** [blackducksoftware/let-me-cluster-that-for-you#4]
Currently, we are mounting ssh folder to docker container for access. We need to remove that dependency

**Comment by yashbhutwala** [comment]
Actually I'm thinking we don't need the user to input the ssh key.  As long as they have cluster-admin access to kubernetes, they can shell into any nodes as root.

**Comment by yashbhutwala** [comment]
Tracking in JIRA.
